"""initial schema

Revision ID: 63e906c1273f
Revises: 
Create Date: 2026-09-11 17:55:45.565847+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e906c1273f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=True),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('confederation', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('data_types', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('update_frequency', sa.String(length=100), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('licence', sa.Text(), nullable=True),
    sa.Column('licence_url', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('commercial_use_allowed', sa.Boolean(), nullable=True),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=True),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('model_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=True),
    sa.Column('n_test', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_version')
    )
    op.create_table('competitions',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('competition_type', sa.Enum('domestic_league', 'domestic_cup', 'international_club', 'international_national', 'youth', 'other', name='competition_type'), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=True),
    sa.Column('is_youth', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('competition_id'),
    sa.UniqueConstraint('name', 'country_id', 'gender', name='uq_competition_identity')
    )
    op.create_table('ingestion_jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'partial', name='job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_jobs_status_started', 'ingestion_jobs', ['status', 'started_at'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('canonical_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('family', sa.Enum('playing_time', 'attacking', 'passing', 'possession', 'defending', 'duels', 'discipline', 'goalkeeping', name='metric_family'), nullable=False),
    sa.Column('scope', sa.Enum('outfield', 'goalkeeper', 'all', name='metric_scope'), nullable=False),
    sa.Column('direction', sa.Enum('higher_better', 'lower_better', 'neutral', name='metric_direction'), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('is_rate', sa.Boolean(), nullable=False),
    sa.Column('per90_eligible', sa.Boolean(), nullable=False),
    sa.Column('derivation_rule', sa.Text(), nullable=True),
    sa.Column('definition_version', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_metric_definitions_canonical_code'), 'metric_definitions', ['canonical_code'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('known_as', sa.String(length=200), nullable=True),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_known_as', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('nationality_country_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('preferred_foot', sa.Enum('left', 'right', 'both', name='preferred_foot'), nullable=True),
    sa.Column('merged_into_player_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR (height_cm BETWEEN 120 AND 230)', name='ck_height_range'),
    sa.ForeignKeyConstraint(['merged_into_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index('ix_players_name_trgm', 'players', ['normalized_name'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_players_normalized_known_as'), 'players', ['normalized_known_as'], unique=False)
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=False)
    op.create_table('position_source_map',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_position_code', sa.String(length=60), nullable=False),
    sa.Column('source_position_name', sa.String(length=100), nullable=True),
    sa.Column('position_code', sa.Enum('GK', 'CB', 'LB', 'RB', 'LWB', 'RWB', 'DM', 'CM', 'AM', 'LW', 'RW', 'SS', 'ST', name='position_code'), nullable=False),
    sa.Column('position_group', sa.Enum('GK', 'CB', 'FB', 'CM', 'AMW', 'ST', name='position_group'), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=True),
    sa.Column('role_variant', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'source_position_code')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('is_national_team', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_normalized_name'), 'teams', ['normalized_name'], unique=False)
    op.create_table('competition_source_ids',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_competition_id', sa.String(length=100), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'source_competition_id')
    )
    op.create_index(op.f('ix_competition_source_ids_competition_id'), 'competition_source_ids', ['competition_id'], unique=False)
    op.create_table('identity_match_candidates',
    sa.Column('candidate_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_player_id', sa.String(length=100), nullable=False),
    sa.Column('internal_player_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking_keys', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'auto_merged', 'superseded', name='match_candidate_status'), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('source_id', 'source_player_id', 'internal_player_id', name='uq_identity_candidate')
    )
    op.create_index('ix_identity_pending', 'identity_match_candidates', ['status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('market_value_references',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'valuation_date', 'source_id')
    )
    op.create_table('player_contracts',
    sa.Column('contract_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='confidence_tier'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_player_contracts_player_id'), 'player_contracts', ['player_id'], unique=False)
    op.create_table('player_source_ids',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_player_id', sa.String(length=100), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'source_player_id')
    )
    op.create_index(op.f('ix_player_source_ids_player_id'), 'player_source_ids', ['player_id'], unique=False)
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.SmallInteger(), nullable=False),
    sa.Column('end_year', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('coverage_type', sa.Enum('full_league', 'tournament', 'single_team', 'partial', 'unknown', name='coverage_type'), nullable=False),
    sa.Column('coverage_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.PrimaryKeyConstraint('season_id'),
    sa.UniqueConstraint('competition_id', 'name', name='uq_season_per_competition')
    )
    op.create_index(op.f('ix_seasons_competition_id'), 'seasons', ['competition_id'], unique=False)
    op.create_table('team_ratings',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=False),
    sa.Column('rating_system', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'rating_date', 'rating_system')
    )
    op.create_index('ix_team_ratings_date', 'team_ratings', ['rating_system', 'rating_date'], unique=False)
    op.create_table('team_source_ids',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_team_id', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'source_team_id')
    )
    op.create_index(op.f('ix_team_source_ids_team_id'), 'team_source_ids', ['team_id'], unique=False)
    op.create_table('transfers',
    sa.Column('transfer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=True),
    sa.Column('from_competition_id', sa.Integer(), nullable=True),
    sa.Column('to_competition_id', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('season_label', sa.String(length=20), nullable=True),
    sa.Column('transfer_type', sa.Enum('permanent', 'loan', 'loan_with_obligation', 'end_of_loan', 'free', 'swap', 'unknown', name='transfer_type'), nullable=False),
    sa.Column('fee_status', sa.Enum('disclosed', 'undisclosed', 'free', 'loan_fee', 'none', 'unknown', name='fee_status'), nullable=False),
    sa.Column('fee_reported', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fee_currency', sa.String(length=3), nullable=True),
    sa.Column('fee_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fee_eur_inflation_adjusted', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('age_at_transfer', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('contract_until', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(fee_status = 'disclosed' AND fee_eur IS NOT NULL) OR fee_status <> 'disclosed'", name='ck_transfer_disclosed_has_fee'),
    sa.ForeignKeyConstraint(['from_competition_id'], ['competitions.competition_id'], ),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['to_competition_id'], ['competitions.competition_id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_index(op.f('ix_transfers_player_id'), 'transfers', ['player_id'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_date'), 'transfers', ['transfer_date'], unique=False)
    op.create_table('data_quality_flags',
    sa.Column('flag_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('flag_code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'error')", name='ck_dq_severity'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_index('ix_dq_entity', 'data_quality_flags', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_dq_open', 'data_quality_flags', ['flag_code'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('league_strength',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('method_version', sa.String(length=30), nullable=False),
    sa.Column('strength_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='confidence_tier'), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('strength_score BETWEEN 0 AND 1', name='ck_strength_range'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('competition_id', 'season_id', 'method_version')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('kick_off', sa.String(length=12), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('match_week', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('available', 'scheduled', 'processing', 'unavailable', name='match_status'), nullable=False),
    sa.Column('regulation_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('elapsed_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('had_penalty_shootout', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_match_id', sa.String(length=100), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_match_distinct_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('source_id', 'source_match_id', name='uq_match_source')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_competition_id'), 'matches', ['competition_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('prediction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('predicted_value_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lower_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('upper_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_tier', sa.Enum('high', 'medium', 'low', 'insufficient', name='confidence_tier'), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('predicted_value_eur >= 0', name='ck_prediction_nonneg'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.run_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('run_id', 'player_id', 'as_of_date', name='uq_prediction_per_run')
    )
    op.create_index(op.f('ix_model_predictions_player_id'), 'model_predictions', ['player_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_run_id'), 'model_predictions', ['run_id'], unique=False)
    op.create_table('player_merges',
    sa.Column('merge_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('survivor_player_id', sa.BigInteger(), nullable=False),
    sa.Column('merged_player_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method IN ('auto', 'manual')", name='ck_merge_method'),
    sa.ForeignKeyConstraint(['candidate_id'], ['identity_match_candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['merged_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['survivor_player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('merge_id')
    )
    op.create_table('player_percentiles',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.Enum('GK', 'CB', 'FB', 'CM', 'AMW', 'ST', name='position_group'), nullable=False),
    sa.Column('family', sa.String(length=10), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('percentile', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('pool_level', sa.SmallInteger(), nullable=False),
    sa.Column('pool_n', sa.Integer(), nullable=False),
    sa.Column('pool_key', sa.String(length=80), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("family IN ('raw', 'adjusted')", name='ck_percentile_family'),
    sa.CheckConstraint('percentile BETWEEN 0 AND 100', name='ck_percentile_range'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.metric_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'position_group', 'family', 'metric_id')
    )
    op.create_table('player_positions',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('position_code', sa.Enum('GK', 'CB', 'LB', 'RB', 'LWB', 'RWB', 'DM', 'CM', 'AM', 'LW', 'RW', 'SS', 'ST', name='position_code'), nullable=False),
    sa.Column('position_group', sa.Enum('GK', 'CB', 'FB', 'CM', 'AMW', 'ST', name='position_group'), nullable=False),
    sa.Column('share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('minutes_nominal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('role_variant', sa.String(length=30), nullable=True),
    sa.Column('position_basis', sa.String(length=30), nullable=False),
    sa.Column('position_confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='confidence_tier'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank IN (1, 2)', name='ck_position_rank'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'rank')
    )
    op.create_index(op.f('ix_player_positions_position_group'), 'player_positions', ['position_group'], unique=False)
    op.create_table('player_profile_vectors',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.Enum('GK', 'CB', 'FB', 'CM', 'AMW', 'ST', name='position_group'), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=64), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_completeness', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'position_group', 'mode')
    )
    op.create_table('player_season_team_stats',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('appearances', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.metric_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'team_id', 'metric_id')
    )
    op.create_table('season_source_ids',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_competition_id', sa.String(length=100), nullable=False),
    sa.Column('source_season_id', sa.String(length=100), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'source_competition_id', 'source_season_id')
    )
    op.create_index(op.f('ix_season_source_ids_season_id'), 'season_source_ids', ['season_id'], unique=False)
    op.create_table('similarity_results',
    sa.Column('target_player_id', sa.BigInteger(), nullable=False),
    sa.Column('target_season_id', sa.Integer(), nullable=False),
    sa.Column('candidate_player_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_season_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('weights_hash', sa.String(length=40), nullable=False),
    sa.Column('sim_stat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('compatibility', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sim_final', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sim_by_category', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usable_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_tier', sa.Enum('high', 'medium', 'low', 'insufficient', name='confidence_tier'), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['candidate_season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['target_season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('target_player_id', 'target_season_id', 'candidate_player_id', 'candidate_season_id', 'mode', 'weights_hash')
    )
    op.create_index('ix_sim_target_rank', 'similarity_results', ['target_player_id', 'target_season_id', 'mode', 'weights_hash', 'rank'], unique=False)
    op.create_table('stat_observations',
    sa.Column('observation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('minutes_basis', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_quality', sa.Enum('event_derived', 'provider_aggregate', 'manual', 'derived', name='data_quality'), nullable=False),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.metric_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index('ix_obs_lookup', 'stat_observations', ['player_id', 'season_id', 'metric_id'], unique=False)
    op.create_index('ix_obs_source', 'stat_observations', ['source_id', 'ingested_at'], unique=False)
    op.create_table('player_match_appearances',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('minutes_nominal', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('minutes_elapsed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('minutes_by_position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jersey_number', sa.SmallInteger(), nullable=True),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=False),
    sa.Column('red_card', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('minutes_nominal >= 0 AND minutes_elapsed >= 0', name='ck_pma_minutes_nonneg'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_index(op.f('ix_player_match_appearances_team_id'), 'player_match_appearances', ['team_id'], unique=False)
    op.create_index('ix_pma_player', 'player_match_appearances', ['player_id'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.metric_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id', 'metric_id')
    )
    op.create_index('ix_pms_player_metric', 'player_match_stats', ['player_id', 'metric_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('per90', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('appearances', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=True),
    sa.Column('resolution_rule', sa.String(length=60), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('minutes >= 0', name='ck_pss_minutes_nonneg'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.metric_id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['stat_observations.observation_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'metric_id')
    )
    op.create_index('ix_pss_season_metric', 'player_season_stats', ['season_id', 'metric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pss_season_metric', table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index('ix_pms_player_metric', table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index('ix_pma_player', table_name='player_match_appearances')
    op.drop_index(op.f('ix_player_match_appearances_team_id'), table_name='player_match_appearances')
    op.drop_table('player_match_appearances')
    op.drop_index('ix_obs_source', table_name='stat_observations')
    op.drop_index('ix_obs_lookup', table_name='stat_observations')
    op.drop_table('stat_observations')
    op.drop_index('ix_sim_target_rank', table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index(op.f('ix_season_source_ids_season_id'), table_name='season_source_ids')
    op.drop_table('season_source_ids')
    op.drop_table('player_season_team_stats')
    op.drop_table('player_profile_vectors')
    op.drop_index(op.f('ix_player_positions_position_group'), table_name='player_positions')
    op.drop_table('player_positions')
    op.drop_table('player_percentiles')
    op.drop_table('player_merges')
    op.drop_index(op.f('ix_model_predictions_run_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_player_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_competition_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('league_strength')
    op.drop_index('ix_dq_open', table_name='data_quality_flags', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index('ix_dq_entity', table_name='data_quality_flags')
    op.drop_table('data_quality_flags')
    op.drop_index(op.f('ix_transfers_transfer_date'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_player_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_team_source_ids_team_id'), table_name='team_source_ids')
    op.drop_table('team_source_ids')
    op.drop_index('ix_team_ratings_date', table_name='team_ratings')
    op.drop_table('team_ratings')
    op.drop_index(op.f('ix_seasons_competition_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_player_source_ids_player_id'), table_name='player_source_ids')
    op.drop_table('player_source_ids')
    op.drop_index(op.f('ix_player_contracts_player_id'), table_name='player_contracts')
    op.drop_table('player_contracts')
    op.drop_table('market_value_references')
    op.drop_index('ix_identity_pending', table_name='identity_match_candidates', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('identity_match_candidates')
    op.drop_index(op.f('ix_competition_source_ids_competition_id'), table_name='competition_source_ids')
    op.drop_table('competition_source_ids')
    op.drop_index(op.f('ix_teams_normalized_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('position_source_map')
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_index(op.f('ix_players_normalized_known_as'), table_name='players')
    op.drop_index('ix_players_name_trgm', table_name='players', postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.drop_table('players')
    op.drop_index(op.f('ix_metric_definitions_canonical_code'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index('ix_jobs_status_started', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('competitions')
    op.drop_table('model_runs')
    op.drop_table('data_sources')
    op.drop_table('countries')
    op.drop_table('analytics_config')
    # ### end Alembic commands ###
    for enum_name in (
        "gender", "competition_type", "coverage_type", "position_code", "position_group",
        "preferred_foot", "metric_family", "metric_direction", "metric_scope", "data_quality",
        "transfer_type", "fee_status", "confidence_tier", "job_status", "match_status",
        "match_candidate_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
